# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
-   repo: local
    hooks:
      - id: isort
        name: sort imports
        entry: isort
        require_serial: true
        language: system
-   repo: local
    hooks:
    - id: flake8
      name: Run flake8
      entry: flake8
      files: "^.py"
      language: system
