name: Tests
on: [push]
jobs:
  pre-commit:
    name: Run pre-commit on all files
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install package including dev dependencies using Poetry
      run: make env-install

    - name: Run pre-commit on all files
      run: pre-commit run --all-files

  pytest:
    name: Run unit-tests using pytest
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install package including dev dependencies using Poetry
      run: make env-install

    - name: Run pytest tests
      run: pytest tests
