name: Tests
on: [push]
jobs:
  pre-commit:
    name: Run pre-commit on all files
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.10"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install the project and devs
      run: uv sync --group dev

    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files


  pytest:
    name: Run unit-tests using pytest
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.10"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install the project and devs
      run: uv sync --group dev

    - name: Run pytest tests
      run: |
        uv run pytest tests
